# Generated by Django 4.1.2 on 2022-10-26 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offence_category', models.CharField(choices=[('Stalking', 'Stalking'), ('Sexual Violence', 'Sexual Violence'), ('Physical Violence', 'Physical Violence'), ('Emotional Violence', 'Emotional Violence'), ('Harmful Traditional Practices', 'Harmful Traditional Practices'), ('Other', 'Other')], max_length=150)),
                ('date_of_incident', models.DateTimeField()),
                ('country_of_incident', models.CharField(choices=[('Mombasa', 'Mombasa'), ('Kwale', 'Kwale'), ('Kilifi', 'Kilifi'), ('Tana_River', 'Tana_River'), ('Lamu', 'Lamu'), ('Taita_Taveta', 'Taita_Taveta'), ('Garissa', 'Garissa'), ('Wajir', 'Wajir'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Isiolo', 'Isiolo'), ('Meru', 'Meru'), ('Tharaka_Nithi', 'Tharaka_Nithi'), ('Embu', 'Embu'), ('Kitui', 'Kitui'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Nyandarua', 'Nyandarua'), ('Nyeri', 'Nyeri'), ('Kirinyaga', 'Kirinyaga'), ('Muranga', 'Muranga'), ('Kiambu', 'Kiambu'), ('Turkana', 'Turkana'), ('West_Pokot', 'West_Pokot'), ('Samburu', 'Samburu'), ('Trans_Nzoia', 'Trans_Nzoia'), ('Uasin_Gishu', 'Uasin_Gishu'), ('Elgey_Marakwet', 'Elgey_Marakwet'), ('Nandi', 'Nandi'), ('Baringo', 'Baringo'), ('Laikipia', 'Laikipia'), ('Nakuru', 'Nakuru'), ('Narok', 'Narok'), ('Kajiado', 'Kajiado'), ('Kericho', 'Kericho'), ('Bomet', 'Bomet'), ('Kakamega', 'Kakamega'), ('Vihiga', 'Vihiga'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Siaya', 'Siaya'), ('Kisumu', 'Kisumu'), ('Homa_Bay', 'Homa_Bay'), ('Migori', 'Migori'), ('Kisii', 'Kisii'), ('Nyamira', 'Nyamira'), ('Nairobi', 'Nairobi')], max_length=100)),
                ('location_of_incident', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('perpetrator_name', models.CharField(max_length=150)),
                ('perpetrator_phone_number', models.CharField(max_length=50)),
                ('perpetrator_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('relationship_to_perpetrator', models.CharField(choices=[('Spouse', 'Spouse'), ('Friend', 'Friend'), ('Relative', 'Relative'), ('Stranger', 'Stranger')], max_length=100)),
                ('perpetrator_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
