# Generated by Django 4.1.2 on 2022-11-13 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_rename_country_of_incident_incident_county_of_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='police',
            field=models.ManyToManyField(related_name='police', to=settings.AUTH_USER_MODEL),
        ),
    ]
