# Generated by Django 4.1.2 on 2022-11-13 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_incident_police'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Pending', 'Pending'), ('Police Added', 'Police Added'), ('Investigation Started', 'Investigation Started'), ('Case Closed', 'Case Closed')], max_length=150)),
                ('desc', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.incident')),
            ],
        ),
    ]
