# Generated by Django 4.1.2 on 2022-11-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_incidentevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentevent',
            name='type',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Police Added', 'Police Added'), ('Investigation Started', 'Investigation Started'), ('Case In Court', 'Case In Court'), ('Case Closed', 'Case Closed')], max_length=150),
        ),
    ]
