# Generated by Django 4.1.2 on 2022-11-14 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_incidentevent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='police',
            field=models.ManyToManyField(blank=True, null=True, related_name='police', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidentevent',
            name='event_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
