# Generated by Django 4.1.2 on 2022-11-20 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_alter_incident_police'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ocs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
