# Generated by Django 4.1.2 on 2022-11-20 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_policestation'),
    ]

    operations = [
        migrations.AddField(
            model_name='policestation',
            name='police',
            field=models.ManyToManyField(related_name='officers', to=settings.AUTH_USER_MODEL),
        ),
    ]
