# Generated by Django 4.1.2 on 2022-11-21 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_policestation_police'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='station',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.policestation'),
        ),
        migrations.AlterField(
            model_name='incidentevent',
            name='type',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Police Added', 'Police Added'), ('Investigation Started', 'Investigation Started'), ('Case In Court', 'Case In Court'), ('Case Closed', 'Case Closed'), ('Police Removed', 'Police Removed'), ('Assigned To Police Station', 'Station Assigned')], max_length=150),
        ),
    ]
