# Generated by Django 4.1.2 on 2022-11-21 00:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_incident_station_alter_incidentevent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='police',
            field=models.ManyToManyField(blank=True, related_name='police', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='police',
            field=models.ManyToManyField(blank=True, related_name='officers', to=settings.AUTH_USER_MODEL),
        ),
    ]
