# Generated by Django 4.1.2 on 2022-11-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_policestation_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='county_of_incident',
            field=models.CharField(choices=[('Mombasa', 'Mombasa'), ('Uasin_Gishu', 'Uasin_Gishu'), ('Nakuru', 'Nakuru'), ('Kisumu', 'Kisumu'), ('Migori', 'Migori'), ('Kisii', 'Kisii'), ('Nairobi', 'Nairobi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='county',
            field=models.TextField(choices=[('Mombasa', 'Mombasa'), ('Uasin_Gishu', 'Uasin_Gishu'), ('Nakuru', 'Nakuru'), ('Kisumu', 'Kisumu'), ('Migori', 'Migori'), ('Kisii', 'Kisii'), ('Nairobi', 'Nairobi')], max_length=100),
        ),
    ]
