# Generated by Django 4.1.2 on 2022-11-22 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_incident_county_of_incident_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
