# Generated by Django 4.1.2 on 2022-11-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_incident_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='reported_by',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
