# Generated by Django 4.1.2 on 2022-11-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Police', 'Police'), ('Admin', 'Admin')], default='User', max_length=30),
        ),
    ]
